from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def require_contains(path: Path, needle: str) -> None:
    text = path.read_text(encoding="utf-8")
    if needle not in text:
        raise SystemExit(f"{path.relative_to(ROOT)} missing required launch contract: {needle!r}")


def require_not_contains(path: Path, needle: str) -> None:
    text = path.read_text(encoding="utf-8")
    if needle in text:
        raise SystemExit(f"{path.relative_to(ROOT)} contains forbidden incompatible launch contract: {needle!r}")


def main() -> None:
    supervisor = ROOT / "scripts" / "start_old_japanese_0_1b_dml_and_watch.ps1"
    watcher = ROOT / "scripts" / "watch_and_finalize_old_japanese_0_1b_dml.ps1"
    non_release_stop = ROOT / "scripts" / "stop_dml_run_as_non_release.ps1"
    direct_gate_test = ROOT / "scripts" / "test_dml_direct_launch_gate.ps1"
    review_gate_launch_test = ROOT / "scripts" / "test_dml_review_gate_launch_guard.ps1"
    autonomous_context_launch_test = ROOT / "scripts" / "test_dml_autonomous_context_launch_guard.ps1"
    entrypoint_gate_test = ROOT / "scripts" / "test_release_training_entrypoint_gates.ps1"

    require_contains(supervisor, "DML train wrapper is not live or does not match RunId after launch")
    require_contains(supervisor, "DML watcher is not live or does not match RunId after launch")
    require_contains(supervisor, "DML active lock was not persisted in running state after launch")
    require_contains(supervisor, "Stop-ProcessTree -RootPid $Watcher.Id")
    require_contains(supervisor, "[IO.FileMode]::CreateNew, [IO.FileAccess]::Write, [IO.FileShare]::None")
    require_contains(supervisor, "[IO.FileMode]::Open, [IO.FileAccess]::ReadWrite, [IO.FileShare]::None")
    require_contains(supervisor, "Refusing to update active lock not owned by this launcher")
    require_contains(supervisor, "Test-ActiveLockOwnedByThisLauncher")
    require_contains(supervisor, "startup_failed_stopped")
    require_contains(supervisor, "Refusing DirectML launch without -AllowStartTraining.")
    require_contains(supervisor, "Refusing DirectML launch without -ReviewsPassed.")
    require_contains(supervisor, "scripts\\verify_preflight_gate.py --gate $PreflightGate")
    require_contains(supervisor, "scripts\\verify_zero_base_review_gate.py --gate $ReviewGate --preflight-gate $PreflightGate")
    require_contains(supervisor, "Refusing DirectML launch because the zero-base review gate is missing")
    require_contains(supervisor, "Refusing DirectML launch without autonomous launch context.")
    require_contains(supervisor, "Assert-AutonomousLaunchContext")
    require_contains(supervisor, "StartsWith($FullRoot, [StringComparison]::OrdinalIgnoreCase)")
    require_not_contains(supervisor, "GetRelativePath")
    require_contains(supervisor, "old_japanese_0_1b_autonomous_launch_context_v1")
    require_contains(supervisor, "preflight_gate_sha256")
    require_contains(supervisor, "review_gate_sha256")
    require_contains(supervisor, "autonomous_launch_context_sha256")
    require_contains(supervisor, "selected_action")
    require_contains(supervisor, "OLD_JAPANESE_REVIEW_GATE")
    require_contains(supervisor, "OLD_JAPANESE_AUTONOMOUS_LAUNCH_CONTEXT")
    require_contains(supervisor, "OLD_JAPANESE_AUTONOMOUS_LAUNCH_NONCE")
    require_contains(supervisor, "launch_nonce_sha256 = $LaunchEvidence.launch_nonce_sha256")
    require_contains(supervisor, "Autonomous launch context nonce hash mismatch.")
    require_contains(supervisor, "Autonomous launch context issuer command line is not an authorized training launch.")
    require_contains(supervisor, "scripts\\assert_run_id_unused.py --run-id $RunId --allow-supervisor-launch-artifacts")
    require_contains(supervisor, "Move-ActiveLockArchive")
    require_contains(supervisor, "active_old_japanese_0_1b_dml.${SafeRunId}.${SafeReason}.")
    require_contains(supervisor, 'Move-ActiveLockArchive -ArchiveRunId ([string]$ExistingLock.run_id) -Reason "stale"')
    require_contains(supervisor, 'if (Test-ActiveLockOwnedByThisLauncher)')
    require_contains(supervisor, 'Move-ActiveLockArchive -ArchiveRunId $RunId -Reason "startup_failed_stopped"')
    require_contains(supervisor, "Not archiving active lock for ${RunId}; active lock is absent or not owned by this launcher.")
    require_contains(supervisor, 'backend = "dml"')
    require_contains(supervisor, "backend_not_dml")
    require_contains(supervisor, "hf_export_not_false")
    require_contains(supervisor, "missing_launch_token_sha256")
    require_contains(supervisor, "missing_launch_nonce_sha256")
    require_contains(supervisor, "missing_preflight_gate")
    require_contains(supervisor, "missing_review_gate")
    require_contains(supervisor, "missing_autonomous_launch_context")
    require_contains(supervisor, "Get-AnySupervisedOldJapaneseProcesses -RequestedRunId")
    require_contains(supervisor, "live supervised old_japanese_0_1b process exists")
    require_contains(supervisor, "Assert-StartupMutexAvailable")
    require_contains(supervisor, "startup_mutex_health")
    require_contains(supervisor, 'sys.path.insert(0, str(Path.cwd() / "scripts"))')
    require_contains(supervisor, "Startup mutex is live, invalid, or unquarantined")
    require_contains(supervisor, "Write-StartupMutexLock")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "scripts\\assert_run_id_unused.py --run-id $RunId --allow-supervisor-launch-artifacts")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "upload_ready_evidence")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "llm_review_packets")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "release")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "*.tmp")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "run_id_reuse_artifacts=")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "--allow-supervisor-launch-artifacts")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "autonomous_launch_context_")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "active_lock_payload_paths")
    require_contains(ROOT / "scripts" / "assert_run_id_unused.py", "logs/active_old_japanese_0_1b_dml*.json")
    require_contains(ROOT / "scripts" / "write_preflight_gate.py", "src/kobun_llm/train.py")
    require_contains(ROOT / "scripts" / "write_preflight_gate.py", "scripts/build_worldclass_corpus.py")
    require_contains(ROOT / "scripts" / "write_preflight_gate.py", "scripts/check_checkpoint_training_inputs.py")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "scripts\\verify_preflight_gate.py --gate $PreflightGate --max-age-minutes 120")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "scripts\\verify_zero_base_review_gate.py --gate $ReviewGate --preflight-gate $PreflightGate --max-age-minutes 120")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "OLD_JAPANESE_REVIEW_GATE")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "OLD_JAPANESE_AUTONOMOUS_LAUNCH_CONTEXT")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "OLD_JAPANESE_AUTONOMOUS_LAUNCH_NONCE")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "Active-run lock autonomous launch nonce hash mismatch.")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "Active-run lock train_pid does not match current wrapper PID")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "Active-run lock launcher_pid is not an ancestor of the train wrapper.")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "Active-run lock launcher_pid is not the authorized DML supervisor for this RunId.")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "Assert-BoundEvidenceFile")
    require_contains(ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1", "scripts\\audit_source_records.py data\\aozora\\sources.json data\\waka\\sources.json")
    text = (ROOT / "scripts" / "train_old_japanese_0_1b_dml.ps1").read_text(encoding="utf-8")
    if "--fix-clean-sha256" in text:
        raise SystemExit("DML train wrapper must not mutate source records with --fix-clean-sha256")
    require_contains(ROOT / "scripts" / "write_zero_base_review_gate.py", "review_packet_sha256")
    require_contains(ROOT / "scripts" / "write_zero_base_review_gate.py", "review_artifacts")
    require_contains(ROOT / "scripts" / "write_zero_base_review_gate.py", "load_artifact")
    require_contains(ROOT / "scripts" / "write_zero_base_review_artifact.py", "prompt_sha256")
    require_contains(ROOT / "scripts" / "write_zero_base_review_artifact.py", "fork_context")
    require_contains(ROOT / "scripts" / "verify_zero_base_review_gate.py", "review_packet_sha256_mismatch")
    require_contains(ROOT / "scripts" / "verify_zero_base_review_gate.py", "review_artifact_packet_hash_mismatch")
    require_contains(ROOT / "scripts" / "write_zero_base_review_gate.py", "duplicate_review_agent_id")
    require_contains(ROOT / "scripts" / "verify_zero_base_review_gate.py", "review_gate_older_than_preflight_gate")
    require_contains(ROOT / "scripts" / "verify_zero_base_review_gate.py", "scope_invalid_agent_id")
    preflight_writer = ROOT / "scripts" / "write_preflight_gate.py"
    require_contains(preflight_writer, "scripts/autonomous_old_japanese_0_1b_loop.ps1")
    require_contains(preflight_writer, "scripts/write_zero_base_review_gate.py")
    require_contains(preflight_writer, "scripts/verify_zero_base_review_gate.py")
    require_contains(preflight_writer, "HASHED_GLOBS")
    require_contains(preflight_writer, "scripts/*.py")
    require_contains(preflight_writer, "src/kobun_llm/*.py")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "stale_artifact_did_not_block_run_id_reuse")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "eval_results_")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "not_upload_ready_diagnostic_")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "autonomous_launch_context_")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "supervisor_launch_context_did_not_block_without_allow_flag")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "hf_model_")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", ".pt.tmp")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "legacy_payload_only")
    require_contains(ROOT / "scripts" / "test_run_id_unused_guard.py", "payload_artifact_did_not_block_run_id_reuse")

    require_contains(watcher, "training_process_exit_code_unavailable")
    require_contains(watcher, "training_process_exit_status_unknown")
    require_contains(watcher, "using_train_exit_sentinel=true")
    require_contains(watcher, "Training exit sentinel is stale")
    require_contains(watcher, "hf_export_policy=watcher_never_exports")

    require_contains(non_release_stop, "No live process found for $RunId; refusing to fabricate a non-release stop.")
    require_contains(non_release_stop, "Refusing non-release record because train exit sentinel reports success")
    require_contains(non_release_stop, "logs\\non_release_runs\\${RunId}.json")
    require_contains(non_release_stop, "source_archive_path = $ArchiveRelativePath")
    require_contains(non_release_stop, "hf_export = $false")

    require_contains(direct_gate_test, "Direct DML launcher unexpectedly succeeded without explicit safe flags.")
    require_contains(direct_gate_test, "Refusing DirectML launch without -AllowStartTraining.")
    require_contains(direct_gate_test, "Direct DML launch gate changed the active lock.")
    require_contains(direct_gate_test, "Direct DML launch gate created artifacts")

    require_contains(review_gate_launch_test, "Direct DML launcher unexpectedly succeeded with a missing zero-base review gate.")
    require_contains(review_gate_launch_test, "Refusing DirectML launch because the zero-base review gate is missing")
    require_contains(review_gate_launch_test, "Missing review-gate launch guard changed the active lock.")
    require_contains(review_gate_launch_test, "Missing review-gate launch guard created artifacts")

    require_contains(autonomous_context_launch_test, "Direct DML launcher unexpectedly succeeded without autonomous launch context.")
    require_contains(autonomous_context_launch_test, "Refusing DirectML launch without autonomous launch context.")
    require_contains(autonomous_context_launch_test, "Missing autonomous-context launch guard changed the active lock.")
    require_contains(autonomous_context_launch_test, "Missing autonomous-context launch guard created artifacts")

    require_contains(entrypoint_gate_test, "Release-candidate training must be started through scripts\\start_old_japanese_0_1b_dml_and_watch.ps1")
    require_contains(entrypoint_gate_test, "Missing or mismatched supervisor RunId context.")
    require_contains(entrypoint_gate_test, "release-shaped training requires --require-supervisor and the supervised launcher context.")
    require_contains(entrypoint_gate_test, "active-run lock is missing train_pid.")
    require_contains(entrypoint_gate_test, "Release training entrypoint gate created artifacts")

    run_static = ROOT / "scripts" / "run_static_quality_checks.ps1"
    autonomous = ROOT / "scripts" / "autonomous_old_japanese_0_1b_loop.ps1"
    require_contains(run_static, "scripts\\write_preflight_gate.py")
    require_contains(run_static, "scripts\\write_static_quality_manifest.py --log $StaticLog --status passed --exit-code 0")
    require_contains(run_static, "-RefreshEvidence")
    require_contains(run_static, "scripts\\verify_static_quality_manifest.py --max-age-minutes 120")
    require_contains(run_static, "scripts\\verify_preflight_gate.py --max-age-minutes 120")
    require_contains(run_static, "scripts\\write_zero_base_review_artifact.py")
    require_contains(run_static, "scripts\\write_zero_base_review_gate.py")
    require_contains(run_static, "scripts\\verify_zero_base_review_gate.py")
    require_contains(run_static, "scripts\\test_zero_base_review_gate.py")
    require_contains(run_static, "scripts\\test_dml_autonomous_context_launch_guard.ps1")
    require_contains(run_static, "scripts\\test_dml_review_gate_launch_guard.ps1")
    require_contains(run_static, "scripts\\test_dml_direct_launch_gate.ps1")
    require_contains(run_static, "scripts\\test_release_training_entrypoint_gates.ps1")
    require_contains(ROOT / "src" / "kobun_autonomy" / "non_release_registry.py", "NonReleaseRecordError")
    require_contains(ROOT / "src" / "kobun_autonomy" / "non_release_registry.py", "non_release_record_status_invalid")
    require_contains(ROOT / "src" / "kobun_autonomy" / "release_policy.py", "refuses untrusted non-release record")
    require_contains(ROOT / "scripts" / "export_hf_release.py", "run_checkpoint_gates(args.checkpoint, args.eval_results")
    require_contains(ROOT / "scripts" / "export_hf_release.py", "verify_eval_quality_log(eval_payload, expected_runner=expected_runner)")
    require_contains(ROOT / "scripts" / "export_hf_release.py", "scripts/run_quality_checks_cuda.py")
    require_contains(ROOT / "scripts" / "export_hf_release.py", "eval quality_runner must be {expected_runner}.")
    require_contains(ROOT / "scripts" / "export_hf_release.py", "eval results do not match canonical evidence reparsed from quality log.")
    finalize = ROOT / "scripts" / "finalize_old_japanese_0_1b_dml.ps1"
    require_contains(finalize, "hf_export_status=skipped_by_finalizer_policy")
    finalizer_text = finalize.read_text(encoding="utf-8")
    if "ExportHf" in finalizer_text or "export_hf_release.py" in finalizer_text or "check_release_package.py" in finalizer_text:
        raise SystemExit("DML finalizer must not expose HF export/package paths")
    dml_quality = ROOT / "scripts" / "run_quality_checks_dml.ps1"
    require_contains(dml_quality, "DML quality checks require the exact best checkpoint file")
    require_contains(dml_quality, "scripts\\check_run_completion.py")
    require_contains(dml_quality, "--require-no-active-process")
    require_contains(dml_quality, "DML quality checkpoint must be checkpoints\\\\<RunId>_best.pt")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "OLD_JAPANESE_REVIEW_GATE")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "OLD_JAPANESE_AUTONOMOUS_LAUNCH_CONTEXT")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "OLD_JAPANESE_AUTONOMOUS_LAUNCH_NONCE")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "Only supervised DirectML or CUDA Colab release-shaped runs are enabled")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "require_python_parent_is_train_wrapper")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "active-run lock train_pid is not in Python ancestor process chain")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "active-run lock launcher_pid is not in Python ancestor process chain.")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "active-run lock launcher_pid is not the authorized DML supervisor for this RunId.")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "verify_autonomous_launch_context_payload")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "verify_bound_runtime_file")
    require_contains(ROOT / "src" / "kobun_llm" / "train.py", "active-run lock {label} hash mismatch")
    require_contains(ROOT / "scripts" / "verify_preflight_gate.py", "static_quality_manifest_hf_export_not_false")
    require_contains(ROOT / "scripts" / "verify_preflight_gate.py", "static_quality_manifest_command_mismatch")
    require_contains(ROOT / "scripts" / "verify_preflight_gate.py", "static_quality_manifest_not_from_explicit_refresh_evidence")
    require_contains(ROOT / "scripts" / "verify_preflight_gate.py", "static_quality_manifest_runner_sha256_mismatch")
    require_contains(ROOT / "scripts" / "verify_preflight_gate.py", "static_quality_manifest_newer_than_preflight_gate")
    require_contains(ROOT / "scripts" / "verify_static_quality_manifest.py", "command_does_not_refresh_evidence")
    progress_reporter = ROOT / "scripts" / "report_old_japanese_0_1b_progress.ps1"
    require_contains(progress_reporter, "Get-ActiveLockForRun")
    require_contains(progress_reporter, "Write-EarlyProgressReport")
    require_contains(progress_reporter, "starting_waiting_for_log")
    require_contains(progress_reporter, "running_waiting_for_first_eval")
    require_contains(autonomous, "-AllowStartTraining -ReviewsPassed")
    require_contains(autonomous, "scripts\\run_static_quality_checks.ps1 -RefreshEvidence")
    require_contains(autonomous, 'param([bool]$RefreshReviewPacket = $true)')
    require_contains(autonomous, 'if ($RefreshReviewPacket)')
    require_contains(autonomous, '$RefreshReviewPacketForMode = $false')
    require_contains(autonomous, 'Update-Board -RefreshReviewPacket $RefreshReviewPacketForMode')
    require_contains(autonomous, 'if ($Action.action -eq "run_post_run_quality_checks")')
    require_contains(autonomous, 'if ($Action.action -eq "fix_blockers")')
    require_contains(autonomous, 'Refusing to start training because selector requested blocker fixes')
    require_contains(autonomous, 'if ($Action.action -ne "prepare_next_fresh_run_after_static_gate_and_zero_base_reviews")')
    require_contains(autonomous, 'Refusing to start training for unsupported selector action')
    require_contains(autonomous, "Verify-ReleaseCandidateStartGates")
    require_contains(autonomous, "scripts\\verify_preflight_gate.py --gate $PreflightGate")
    require_contains(autonomous, "scripts\\verify_zero_base_review_gate.py --gate $ReviewGate --preflight-gate $PreflightGate")
    require_contains(supervisor, "function Assert-NoActiveColabCudaLease")
    require_contains(supervisor, "colab_cuda_lease_health")
    require_contains(supervisor, "Colab CUDA active lease exists")

    print("dml_supervisor_static_contracts_ok=true")


if __name__ == "__main__":
    main()
